CC=gcc 
CFLAGS=-W -Wall -Werror -Wfatal-errors
EXEC=Super_jeu
SRC=$(wildcard *.c)
HFILES=$(wildcard *.h)
OBJ= $(SRC:.c=.o)

all: $(EXEC) 

$(EXEC): $(OBJ) 
	$(CC) -o $(EXEC) $(OBJ) 
	
main.o: $(HFILES)

%.o: %.c 
	$(CC) -o $@ -c $< $(CFLAGS) 


	
