CC=gcc 
CFLAGS=-W -Wall -Werror -Wfatal-errors
LDFLAGS= 
EXEC=Super_jeu
SRC= sudoku.c morpion.c main.c 
OBJ= $(SRC:.c=.o) 

all: $(EXEC) 

Super_jeu: $(OBJ) 
	$(CC) -o $@ $^ $(LDFLAGS) 
	
main.o: sudoku.h morpion.h

%.o: %.c 
	$(CC) -o $@ -c $< $(CFLAGS) 
	
.PHONY: clean mrproper 

clean: 
	@rm -rf *.o 

mrproper: clean 
	@rm -rf $(EXEC)